import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Web3Providers } from "./providers";

// Titles / Headers: League Spartan (local)
const leagueSpartan = localFont({
  variable: "--font-title",
  src: [
    { path: "../public/Fonts/LeagueSpartan/LeagueSpartan-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/Fonts/LeagueSpartan/LeagueSpartan-Medium.ttf", weight: "500", style: "normal" },
    { path: "../public/Fonts/LeagueSpartan/LeagueSpartan-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../public/Fonts/LeagueSpartan/LeagueSpartan-Bold.ttf", weight: "700", style: "normal" },
  ],
});

// Aeonik (local)
const aeonik = localFont({
  variable: "--font-ui",
  src: [
    { path: "../public/Fonts/Aeonik/fonnts.com-Aeonik-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/Fonts/Aeonik/fonnts.com-Aeonik-Bold.ttf", weight: "700", style: "normal" },
  ],
  fallback: ["system-ui", "Segoe UI", "Roboto", "Helvetica Neue", "Arial"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="celestia">
      <body className={`${leagueSpartan.variable} ${aeonik.variable} antialiased`}>
        <Web3Providers>
          {children}
        </Web3Providers>
      </body>
    </html>
  );
}
